Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: Catkin
+name: CI
 
 on: 
   pull_request:
@@ -24,7 +24,7 @@ jobs:
         path: src/franka_ros
     
     - name: Parse ROS Distro
-      run: echo "ROS_DISTRO=$(echo ${{ github.event.pull_request.base.ref }} | sed 's/-devel//')" >> $GITHUB_ENV
+      run:  echo "ROS_DISTRO=$(echo ${{ github.event.pull_request.base.ref }} | sed 's/-devel//')" >> $GITHUB_ENV
     
     - name: Build Docker Image
       uses: docker/build-push-action@v2
@@ -36,8 +36,8 @@ jobs:
     - name: Compile with Catkin Tools
       uses: addnab/docker-run-action@v3
       with:
-        image: franka_ros:${{env.ROS_DISTRO}}
-        options: -v ${{github.workspace}}/src:/ros/src/  # only mount source here
+        image:    franka_ros:${{env.ROS_DISTRO}}
+        options:  -v ${{github.workspace}}/src:/ros/src/  # only mount source here
         run: |
           catkin config --workspace /ros/ --init --extend /opt/ros/${{env.ROS_DISTRO}} --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
           catkin build --workspace /ros/ --interleave-output --verbose
@@ -45,9 +45,9 @@ jobs:
     - name: Compile with Catkin Make
       uses: addnab/docker-run-action@v3
       with:
-        image: franka_ros:${{env.ROS_DISTRO}}
-        options: -v ${{github.workspace}}:/ros
-        shell: bash
+        image:    franka_ros:${{env.ROS_DISTRO}}
+        options:  -v ${{github.workspace}}:/ros
+        shell:    bash
         run: |
           source /opt/ros/${{env.ROS_DISTRO}}/setup.bash
           catkin_init_workspace /ros/src
@@ -57,9 +57,9 @@ jobs:
     - name: Check Format
       uses: addnab/docker-run-action@v3
       with: 
-        image: franka_ros:${{env.ROS_DISTRO}}
-        options: -v ${{github.workspace}}:/ros/
-        shell: bash
+        image:    franka_ros:${{env.ROS_DISTRO}}
+        options:  -v ${{github.workspace}}:/ros/
+        shell:    bash
         run: |
           source /ros/devel/setup.bash
           cmake --build /ros/build --target check-format
@@ -67,9 +67,9 @@ jobs:
     - name: Check Linting
       uses: addnab/docker-run-action@v3
       with: 
-        image: franka_ros:${{env.ROS_DISTRO}}
-        options: -v ${{github.workspace}}:/ros/
-        shell: bash
+        image:    franka_ros:${{env.ROS_DISTRO}}
+        options:  -v ${{github.workspace}}:/ros/
+        shell:    bash
         run: |
           source /ros/devel/setup.bash
           cmake --build /ros/build --target check-format
@@ -77,19 +77,25 @@ jobs:
     - name: Run Tests
       uses: addnab/docker-run-action@v3
       with:
-        image: franka_ros:${{env.ROS_DISTRO}}
-        options: -v ${{github.workspace}}:/ros/
-        shell: bash
+        image:    franka_ros:${{env.ROS_DISTRO}}
+        options:  -v ${{github.workspace}}:/ros/
+        shell:    bash
         run: |
           source /ros/devel/setup.bash
           cd /ros
           catkin_make run_tests
-          
-    - name: Report Test Results
-      uses: dorny/test-reporter@v1
-      if: success() || failure()    # run this step even if previous step failed
+    
+    - name: Upload Tests to Artifacts
+      uses: actions/upload-artifacts@v2
+      if:   success() || failure()    # run this step even if previous step failed
       with:
-        name: ROS-Unit Tests
-        path: build/test_results/*/rosunit-*.xml 
-        working-directory: src/franka_ros
-        reporter: java-junit
+        name: test-results
+        path: build/test_results/*/rosunit-*.xml
+        
+    - name: Create Test Report
+      uses: dorny/test-reporter@v1
+      with:
+        artifacts: test-tesults
+        name:      ROS-Unit Tests
+        path:      '*.xml'           # Path to test results (inside artifact .zip)
+        reporter:  java-junit
